In [1]:
import requests
import pandas as pd
import numpy as np

pd.options.display.max_columns=None

In [2]:
url = 'https://fantasy.premierleague.com/api/bootstrap-static/'

In [3]:
r = requests.get(url)
json = r.json()
json.keys()

dict_keys(['events', 'game_settings', 'phases', 'teams', 'total_players', 'elements', 'element_stats', 'element_types'])

In [4]:
elements_df = pd.DataFrame(json['elements'])
elements_types_df = pd.DataFrame(json['element_types'])
teams_df = pd.DataFrame(json['teams'])
events_df = pd.DataFrame(json['events'])
phases_df = pd.DataFrame(json['phases'])
element_stats_df = pd.DataFrame(json['element_stats'])

In [5]:
elements_types_df

,id,plural_name,plural_name_short,singular_name,singular_name_short,squad_select,squad_min_play,squad_max_play,ui_shirt_specific,sub_positions_locked,element_count
0,1,Goalkeepers,GKP,Goalkeeper,GKP,2,1,1,True,[12],73
1,2,Defenders,DEF,Defender,DEF,5,3,5,False,[],225
2,3,Midfielders,MID,Midfielder,MID,5,2,5,False,[],254
3,4,Forwards,FWD,Forward,FWD,3,1,3,False,[],81

In [6]:
elements_df.head(10)

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,id,in_dreamteam,news,news_added,now_cost,photo,points_per_game,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text
0,0.0,0.0,37605,0,0,-2,2,0,3,0.0,0.0,0,Mesut,0.0,1,False,Not included in Arsenal's 25-man Premier Leagu...,2020-10-20T22:30:18.118477Z,68,37605.jpg,0.0,Ã–zil,0.5,False,None,n,1,3,0,3433,4,53383,70,0.0,0.0,Ã–zil,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,633,254,633,254,633,254,633,254,NaN,,NaN,,NaN,
1,0.0,0.0,39476,0,0,-2,2,0,2,0.0,0.0,0,Sokratis,0.0,2,False,Not included in Arsenal's 25-man Premier Leagu...,2020-10-21T10:30:18.546407Z,48,39476.jpg,0.0,Papastathopoulos,0.1,False,None,n,1,3,0,10264,0,18912,7,0.0,0.0,Sokratis,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,591,216,581,216,573,213,593,216,NaN,,NaN,,NaN,
2,100.0,100.0,41270,0,0,-1,1,0,2,1.7,1.7,5,David,1.2,3,False,,2020-12-26T18:00:15.638627Z,54,41270.jpg,1.6,Luiz Moreira Marinho,0.7,False,None,a,1,3,14,41296,340,91580,274,0.2,2.6,David Luiz,569,0,0,1,9,0,0,0,1,0,0,0,89,111.4,27.5,42.0,18.1,255,98,303,95,270,84,301,99,NaN,,4.0,,NaN,
3,100.0,100.0,54694,0,0,-7,7,1,3,3.7,3.7,3,Pierre-Emerick,3.2,4,False,,2020-12-19T20:30:20.434896Z,113,54694.jpg,3.5,Aubameyang,7.0,False,None,a,1,3,56,522583,850,3182134,7501,0.3,5.0,Aubameyang,1436,3,1,6,16,1,0,0,2,0,0,4,165,211.0,222.6,462.0,89.6,145,56,62,43,23,13,36,23,NaN,,NaN,,1.0,
4,100.0,100.0,58822,0,0,-4,4,0,2,0.7,0.7,0,CÃ©dric,0.2,5,False,,2020-09-23T09:00:14.881983Z,46,58822.jpg,1.0,Soares,0.2,False,None,a,1,3,1,4285,52,35151,102,0.0,0.2,CÃ©dric,5,0,0,0,0,0,0,0,0,0,0,0,3,0.0,0.0,0.0,0.0,578,212,566,213,554,208,581,213,NaN,,NaN,,NaN,
5,NaN,NaN,59966,0,0,-2,2,1,4,5.5,5.5,2,Alexandre,5.0,6,False,,None,83,59966.jpg,4.0,Lacazette,6.5,False,None,a,1,3,60,710720,31354,546757,43095,0.6,7.2,Lacazette,941,7,0,4,8,0,0,0,2,0,0,9,221,309.4,163.0,436.0,90.6,59,9,101,11,27,12,34,12,NaN,,NaN,,3.0,
6,100.0,100.0,69140,0,0,0,0,0,2,0.7,0.7,0,Shkodran,0.2,7,False,,2020-08-15T10:00:11.331812Z,50,69140.jpg,1.0,Mustafi,0.1,False,None,a,1,3,3,13092,55,12899,86,0.0,0.6,Mustafi,45,0,0,0,1,0,0,0,0,0,0,0,16,11.6,1.0,0.0,1.3,417,164,411,161,598,221,436,166,NaN,,NaN,,NaN,
7,NaN,NaN,80201,1,-1,0,0,2,1,5.5,5.5,6,Bernd,5.0,8,False,,None,50,80201.jpg,4.1,Leno,9.1,False,None,a,1,3,73,696489,11317,642060,19536,1.0,14.6,Leno,1620,0,0,6,19,0,1,0,0,0,43,6,345,372.8,0.0,0.0,37.3,32,12,605,63,600,62,191,12,NaN,,NaN,,NaN,
8,100.0,100.0,84450,0,0,-3,3,0,3,3.3,3.3,3,Granit,2.8,9,False,,2020-12-13T22:30:16.182130Z,52,84450.jpg,2.2,Xhaka,0.4,False,None,a,1,3,31,31407,303,66630,622,0.5,6.0,Xhaka,1084,1,0,5,12,0,0,0,2,1,0,1,154,185.6,68.7,75.0,32.9,170,67,211,128,203,109,220,104,NaN,,1.0,,NaN,
9,75.0,100.0,92371,0,0,-1,1,0,2,2.1,2.8,0,Pablo,2.3,10,False,Calf injury - 75% chance of playing,2021-01-14T22:00:26.195009Z,44,92371.jpg,4.7,MarÃ­,0.3,False,None,d,1,3,14,30645,1309,10206,2893,0.5,3.2,MarÃ­,270,0,0,2,1,0,0,0,1,0,0,1,63,59.0,11.7,4.0,7.4,328,125,353,129,384,148,369,135,NaN,,NaN,,NaN,

In [7]:
elements_df.insert(2, "valuePerMinute", [21, 23, 24, 21], True)

ValueError: Length of values (4) does not match length of index (633)

In [8]:
df_slim_elements = elements_df[['second_name','first_name','team','element_type', 'ep_next',
       'ep_this','event_points','selected_by_percent','now_cost','minutes','transfers_in','goals_scored',
       'assists','clean_sheets','goals_conceded','form','value_season','total_points']]

In [9]:
df_slim_elements.head()

,second_name,first_name,team,element_type,ep_next,ep_this,event_points,selected_by_percent,now_cost,minutes,transfers_in,goals_scored,assists,clean_sheets,goals_conceded,form,value_season,total_points
0,Ã–zil,Mesut,1,3,0.0,0.0,0,0.5,68,0,3433,0,0,0,0,0.0,0.0,0
1,Papastathopoulos,Sokratis,1,2,0.0,0.0,0,0.1,48,0,10264,0,0,0,0,0.0,0.0,0
2,Luiz Moreira Marinho,David,1,2,1.7,1.7,5,0.7,54,569,41296,0,0,1,9,1.2,2.6,14
3,Aubameyang,Pierre-Emerick,1,3,3.7,3.7,3,7.0,113,1436,522583,3,1,6,16,3.2,5.0,56
4,Soares,CÃ©dric,1,2,0.7,0.7,0,0.2,46,5,4285,0,0,0,0,0.2,0.2,1

In [23]:
df_inform=df_slim_elements[df_slim_elements['form'] > '4']

In [24]:
df_inform.head(30).to_json()

'{"second_name":{"5":"Lacazette","7":"Leno","14":"Holding","15":"Tierney","22":"Saka","33":"Mart\\u00ednez","43":"Grealish","45":"Hause","48":"Targett","51":"El Ghazi","60":"Cash","62":"Traor\\u00e9","71":"Dunk","110":"Mee","118":"Pope","147":"Abraham","164":"Guaita","192":"Sigurdsson","198":"Keane","204":"Mina","207":"Holgate","246":"Areola","250":"Aina","252":"Adarabioyo","262":"Vardy","272":"Barnes","290":"Dallas","291":"Alioski","292":"Bamford","293":"Harrison"},"first_name":{"5":"Alexandre","7":"Bernd","14":"Rob","15":"Kieran","22":"Bukayo","33":"Emiliano","43":"Jack","45":"Kortney","48":"Matt","51":"Anwar","60":"Matthew","62":"Bertrand","71":"Lewis","110":"Ben","118":"Nick","147":"Tammy","164":"Vicente","192":"Gylfi","198":"Michael","204":"Yerry","207":"Mason","246":"Alphonse","250":"Ola","252":"Tosin","262":"Jamie","272":"Harvey","290":"Stuart","291":"Ezgjan","292":"Patrick","293":"Jack"},"team":{"5":1,"7":1,"14":1,"15":1,"22":1,"33":2,"43":2,"45":2,"48":2,"51":2,"60":2,"62":2,"71":3,"110":4,"118":4,"147":5,"164":6,"192":7,"198":7,"204":7,"207":7,"246":8,"250":8,"252":8,"262":9,"272":9,"290":10,"291":10,"292":10,"293":10},"element_type":{"5":4,"7":1,"14":2,"15":2,"22":3,"33":1,"43":3,"45":2,"48":2,"51":3,"60":2,"62":3,"71":2,"110":2,"118":1,"147":4,"164":1,"192":3,"198":2,"204":2,"207":2,"246":1,"250":2,"252":2,"262":4,"272":3,"290":2,"291":2,"292":4,"293":3},"ep_next":{"5":"5.5","7":"5.5","14":"5.2","15":"4.1","22":"6.2","33":"11.0","43":"8.6","45":"10.2","48":"7.4","51":"13.8","60":"7.0","62":"11.8","71":"4.3","110":"8.8","118":"8.4","147":"10.6","164":"4.0","192":"0.0","198":"0.0","204":"0.0","207":"0.0","246":"9.6","250":"6.0","252":"10.0","262":"10.5","272":"9.3","290":"6.2","291":"5.2","292":"5.2","293":"5.4"},"ep_this":{"5":"5.5","7":"5.5","14":"5.2","15":"5.5","22":"6.2","33":"0.0","43":"0.0","45":"0.0","48":"0.0","51":"0.0","60":"0.0","62":"0.0","71":"3.3","110":"4.4","118":"4.2","147":"0.0","164":"4.5","192":"5.2","198":"5.4","204":"5.6","207":"5.2","246":"4.8","250":"3.0","252":"5.0","262":"0.0","272":"0.0","290":"0.0","291":"0.0","292":"0.0","293":"0.0"},"event_points":{"5":2,"7":6,"14":6,"15":0,"22":3,"33":0,"43":0,"45":0,"48":0,"51":0,"60":0,"62":0,"71":2,"110":2,"118":4,"147":0,"164":10,"192":2,"198":11,"204":2,"207":1,"246":3,"250":2,"252":2,"262":0,"272":0,"290":0,"291":0,"292":0,"293":0},"selected_by_percent":{"5":"6.5","7":"9.1","14":"4.1","15":"9.0","22":"9.2","33":"30.6","43":"36.0","45":"0.6","48":"4.6","51":"3.8","60":"1.1","62":"0.5","71":"2.5","110":"1.7","118":"10.6","147":"3.5","164":"3.2","192":"2.0","198":"5.7","204":"3.7","207":"1.5","246":"2.3","250":"0.5","252":"0.4","262":"26.2","272":"4.2","290":"15.2","291":"3.1","292":"49.1","293":"2.6"},"now_cost":{"5":83,"7":50,"14":45,"15":54,"22":53,"33":51,"43":77,"45":44,"48":46,"51":58,"60":50,"62":59,"71":48,"110":49,"118":54,"147":72,"164":48,"192":68,"198":51,"204":56,"207":48,"246":45,"250":45,"252":45,"262":101,"272":68,"290":48,"291":45,"292":66,"293":54},"minutes":{"5":941,"7":1620,"14":1305,"15":1430,"22":1323,"33":1350,"43":1350,"45":360,"48":1350,"51":478,"60":1222,"62":607,"71":1350,"110":900,"118":1350,"147":777,"164":1620,"192":895,"198":1415,"204":1350,"207":711,"246":1350,"250":1170,"252":1080,"262":1299,"272":1189,"290":1520,"291":971,"292":1456,"293":1309},"transfers_in":{"5":710720,"7":696489,"14":504108,"15":655172,"22":847183,"33":2650856,"43":4331487,"45":68939,"48":562091,"51":418474,"60":130051,"62":59888,"71":112437,"110":167799,"118":397652,"147":385956,"164":391485,"192":165645,"198":685029,"204":364080,"207":156821,"246":185101,"250":59596,"252":41712,"262":3008418,"272":790822,"290":1393450,"291":320255,"292":4987588,"293":482233},"goals_scored":{"5":7,"7":0,"14":0,"15":1,"22":3,"33":0,"43":5,"45":1,"48":0,"51":5,"60":0,"62":3,"71":2,"110":1,"118":0,"147":6,"164":0,"192":2,"198":3,"204":2,"207":1,"246":0,"250":1,"252":0,"262":11,"272":5,"290":3,"291":2,"292":10,"293":3},"assists":{"5":0,"7":0,"14":1,"15":2,"22":2,"33":0,"43":9,"45":0,"48":1,"51":0,"60":2,"62":2,"71":0,"110":0,"118":0,"147":2,"164":0,"192":2,"198":0,"204":0,"207":0,"246":0,"250":0,"252":1,"262":8,"272":1,"290":2,"291":0,"292":5,"293":4},"clean_sheets":{"5":4,"7":6,"14":6,"15":5,"22":5,"33":8,"43":8,"45":3,"48":8,"51":3,"60":7,"62":3,"71":2,"110":5,"118":6,"147":5,"164":3,"192":4,"198":4,"204":4,"207":3,"246":3,"250":3,"252":3,"262":4,"272":3,"290":6,"291":5,"292":6,"293":6},"goals_conceded":{"5":8,"7":19,"14":14,"15":18,"22":15,"33":16,"43":16,"45":1,"48":16,"51":3,"60":16,"62":8,"71":26,"110":9,"118":16,"147":9,"164":29,"192":10,"198":20,"204":17,"207":7,"246":21,"250":14,"252":13,"262":19,"272":17,"290":32,"291":20,"292":31,"293":29},"form":{"5":"5.0","7":"5.0","14":"4.7","15":"5.0","22":"5.7","33":"6.0","43":"4.8","45":"5.6","48":"4.2","51":"7.4","60":"4.0","62":"6.4","71":"4.3","110":"5.4","118":"5.2","147":"4.8","164":"5.0","192":"5.2","198":"5.4","204":"5.6","207":"5.2","246":"5.8","250":"4.0","252":"6.0","262":"5.0","272":"4.4","290":"6.2","291":"5.2","292":"5.2","293":"5.4"},"value_season":{"5":"7.2","7":"14.6","14":"11.6","15":"10.9","22":"11.1","33":"16.3","43":"12.6","45":"6.4","48":"12.2","51":"8.1","60":"10.6","62":"7.8","71":"7.7","110":"10.2","118":"14.6","147":"8.3","164":"12.9","192":"7.8","198":"12.7","204":"10.0","207":"7.1","246":"11.8","250":"9.8","252":"8.9","262":"11.1","272":"9.6","290":"14.8","291":"11.8","292":"15.3","293":"12.4"},"total_points":{"5":60,"7":73,"14":52,"15":59,"22":59,"33":83,"43":97,"45":28,"48":56,"51":47,"60":53,"62":46,"71":37,"110":50,"118":79,"147":60,"164":62,"192":53,"198":65,"204":56,"207":34,"246":53,"250":44,"252":40,"262":112,"272":65,"290":71,"291":53,"292":101,"293":67}}'

In [25]:
df_inform[df_inform['ep_next'] > '12.0']

,second_name,first_name,team,element_type,ep_next,ep_this,event_points,selected_by_percent,now_cost,minutes,transfers_in,goals_scored,assists,clean_sheets,goals_conceded,form,value_season,total_points
5,Lacazette,Alexandre,1,4,5.5,5.5,2,6.5,83,941,710720,7,0,4,8,5.0,7.2,60
7,Leno,Bernd,1,1,5.5,5.5,6,9.1,50,1620,696489,0,0,6,19,5.0,14.6,73
14,Holding,Rob,1,2,5.2,5.2,6,4.1,45,1305,504108,0,1,6,14,4.7,11.6,52
15,Tierney,Kieran,1,2,4.1,5.5,0,9.0,54,1430,655172,1,2,5,18,5.0,10.9,59
22,Saka,Bukayo,1,3,6.2,6.2,3,9.2,53,1323,847183,3,2,5,15,5.7,11.1,59
43,Grealish,Jack,2,3,8.6,0.0,0,36.0,77,1350,4331487,5,9,8,16,4.8,12.6,97
48,Targett,Matt,2,2,7.4,0.0,0,4.6,46,1350,562091,0,1,8,16,4.2,12.2,56
51,El Ghazi,Anwar,2,3,13.8,0.0,0,3.8,58,478,418474,5,0,3,3,7.4,8.1,47
60,Cash,Matthew,2,2,7.0,0.0,0,1.1,50,1222,130051,0,2,7,16,4.0,10.6,53
71,Dunk,Lewis,3,2,4.3,3.3,2,2.5,48,1350,112437,2,0,2,26,4.3,7.7,37
110,Mee,Ben,4,2,8.8,4.4,2,1.7,49,900,167799,1,0,5,9,5.4,10.2,50
118,Pope,Nick,4,1,8.4,4.2,4,10.6,54,1350,397652,0,0,6,16,5.2,14.6,79
164,Guaita,Vicente,6,1,4.0,4.5,10,3.2,48,1620,391485,0,0,3,29,5.0,12.9,62
246,Areola,Alphonse,8,1,9.6,4.8,3,2.3,45,1350,185101,0,0,3,21,5.8,11.8,53
250,Aina,Ola,8,2,6.0,3.0,2,0.5,45,1170,59596,1,0,3,14,4.0,9.8,44
272,Barnes,Harvey,9,3,9.3,0.0,0,4.2,68,1189,790822,5,1,3,17,4.4,9.6,65
290,Dallas,Stuart,10,2,6.2,0.0,0,15.2,48,1520,1393450,3,2,6,32,6.2,14.8,71
291,Alioski,Ezgjan,10,2,5.2,0.0,0,3.1,45,971,320255,2,0,5,20,5.2,11.8,53
292,Bamford,Patrick,10,4,5.2,0.0,0,49.1,66,1456,4987588,10,5,6,31,5.2,15.3,101
293,Harrison,Jack,10,3,5.4,0.0,0,2.6,54,1309,482233,3,4,6,29,5.4,12.4,67
303,Meslier,Illan,10,1,4.2,0.0,0,6.7,46,1530,684108,0,0,6,33,4.2,15.2,70
307,Moreno,Rodrigo,10,4,5.0,0.0,0,3.3,57,814,303387,3,2,2,17,5.0,8.4,48
311,Dias Belloli,Raphael,10,3,4.4,0.0,0,1.8,55,833,230228,2,2,4,17,4.4,7.3,40
323,Firmino,Roberto,11,4,14.4,0.0,0,4.6,93,1393,470837,5,3,5,19,6.2,7.5,70
328,Salah,Mohamed,11,3,14.0,0.0,0,39.1,125,1348,3617445,13,4,4,20,6.0,10.0,125
329,Robertson,Andrew,11,2,12.8,0.0,0,21.4,74,1530,1938317,1,5,5,21,5.4,10.8,80
351,GÃ¼ndogan,Ilkay,12,3,15.0,7.5,3,2.6,55,824,244212,3,0,6,3,6.5,8.7,48
352,De Bruyne,Kevin,12,3,15.6,7.8,6,27.3,118,1277,3747894,3,9,8,11,6.8,7.4,87
353,Stones,John,12,2,13.0,6.5,6,8.0,50,720,698351,0,0,6,2,5.5,8.8,44
357,Cancelo,JoÃ£o Pedro Cavaco,12,2,13.6,6.8,6,11.7,58,1080,1162868,0,1,7,6,5.8,10.5,61
364,Foden,Phil,12,3,15.0,7.5,11,7.1,63,668,1272709,4,3,3,6,6.5,9.4,59
373,Gato Alves Dias,RÃºben Santos,12,2,14.0,7.0,7,9.7,58,1239,942248,0,0,8,7,6.0,10.2,59
386,Pogba,Paul,13,3,8.5,3.8,11,1.5,77,947,146180,2,2,3,14,4.0,6.2,48
392,Borges Fernandes,Bruno Miguel,13,3,16.9,9.2,2,52.9,113,1387,4350855,11,8,5,19,8.2,11.7,132
396,Rashford,Marcus,13,3,13.1,7.3,6,12.3,96,1442,1691271,7,5,5,22,6.3,9.4,90
399,McTominay,Scott,13,3,8.9,5.2,1,1.3,49,920,141720,2,1,2,14,4.2,8.8,43
450,McGoldrick,David,15,4,3.5,4.0,1,2.0,52,1011,245250,4,1,5,15,4.0,9.4,49
476,Walcott,Theo,16,3,3.5,0.0,0,0.9,58,1019,156136,2,3,5,14,4.0,8.8,51
479,McCarthy,Alex,16,1,3.7,0.0,0,20.1,47,1440,1130946,0,0,7,19,4.2,15.1,71
483,Stephens,Jack,16,2,4.1,0.0,0,0.3,46,585,14645,0,0,4,9,4.6,6.7,31
490,Walker-Peters,Kyle,16,2,4.1,0.0,0,14.0,48,1530,1062301,0,2,8,19,4.6,14.4,69
491,Bednarek,Jan,16,2,4.7,0.0,0,12.9,49,1440,1136880,1,1,8,16,5.2,16.1,79
506,Lloris,Hugo,17,1,4.5,5.0,3,7.9,56,1530,571181,0,0,6,16,4.0,13.6,76
511,Kane,Harry,17,4,5.7,6.2,8,44.3,111,1519,3887447,11,11,6,15,5.2,12.0,133
513,Son,Heung-Min,17,3,6.3,6.8,2,61.4,98,1436,5849257,12,5,8,10,5.8,13.7,134
588,Soucek,Tomas,19,3,12.2,0.0,0,15.5,53,1530,1411974,5,1,6,21,5.6,14.5,77
602,SaÃ¯ss,Romain,20,2,4.7,4.2,1,10.5,51,1147,2140148,3,0,4,18,4.2,12.4,63
607,da Silva Neves,RÃºben Diogo,20,3,5.1,4.6,7,1.4,52,1239,72191,2,0,3,22,4.6,8.7,45

In [20]:
fpl_html = df_inform.sort_values('ep_next', ascending=False)
fpl_html

,second_name,first_name,team,element_type,ep_next,ep_this,event_points,selected_by_percent,now_cost,minutes,transfers_in,goals_scored,assists,clean_sheets,goals_conceded,form,value_season,total_points
246,Areola,Alphonse,8,1,9.6,4.8,3,2.3,45,1350,185101,0,0,3,21,5.8,11.8,53
272,Barnes,Harvey,9,3,9.3,0.0,0,4.2,68,1189,790822,5,1,3,17,4.4,9.6,65
399,McTominay,Scott,13,3,8.9,5.2,1,1.3,49,920,141720,2,1,2,14,4.2,8.8,43
110,Mee,Ben,4,2,8.8,4.4,2,1.7,49,900,167799,1,0,5,9,5.4,10.2,50
43,Grealish,Jack,2,3,8.6,0.0,0,36.0,77,1350,4331487,5,9,8,16,4.8,12.6,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,Adarabioyo,Tosin,8,2,10.0,5.0,2,0.4,45,1080,41712,0,1,3,13,6.0,8.9,40
204,Mina,Yerry,7,2,0.0,5.6,2,3.7,56,1350,364080,2,0,4,17,5.6,10.0,56
192,Sigurdsson,Gylfi,7,3,0.0,5.2,2,2.0,68,895,165645,2,2,4,10,5.2,7.8,53
198,Keane,Michael,7,2,0.0,5.4,11,5.7,51,1415,685029,3,0,4,20,5.4,12.7,65
207,Holgate,Mason,7,2,0.0,5.2,1,1.5,48,711,156821,1,0,3,7,5.2,7.1,34

In [54]:
df_exspense=df_slim_elements[df_slim_elements['now_cost'] > 85]
minuteValue = df_slim_elements[df_slim_elements['total_points']] / df_slim_elements[df_slim_elements['now_cost']] * df_slim_elements[df_slim_elements['minutes']]/(90*8)

In [22]:
df_slim_elements['position'] = df_slim_elements.element_type.map(elements_types_df.set_index('id').singular_name)

<ipython-input-22-48d4fef8b31c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_slim_elements['position'] = df_slim_elements.element_type.map(elements_types_df.set_index('id').singular_name)

In [70]:
df_slim_elements['team'] = df_slim_elements.team.map(teams_df.set_index('id').name)

<ipython-input-70-e0976f04ef24>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_slim_elements['team'] = df_slim_elements.team.map(teams_df.set_index('id').name)

In [107]:
df_slim_elements.head().to_json(orient="records")

'[{"second_name":"\\u00d6zil","team":1,"event_points":0,"selected_by_percent":"0.6","now_cost":68},{"second_name":"Papastathopoulos","team":1,"event_points":0,"selected_by_percent":"0.1","now_cost":49},{"second_name":"Luiz Moreira Marinho","team":1,"event_points":0,"selected_by_percent":"0.9","now_cost":55},{"second_name":"Aubameyang","team":1,"event_points":2,"selected_by_percent":"13.1","now_cost":117},{"second_name":"Soares","team":1,"event_points":0,"selected_by_percent":"0.2","now_cost":47}]'

In [72]:
df_slim_elements['value'] = df_slim_elements.value_season.astype(float)

<ipython-input-72-076ae1b21e5c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_slim_elements['value'] = df_slim_elements.value_season.astype(float)

In [98]:
df_slim_elements.sort_values('ep_next', ascending=False).head(5).to_json(orient="records")

'[{"second_name":"Borges Fernandes","first_name":"Bruno Miguel","team":"Man Utd","element_type":3,"ep_next":"9.2","ep_this":"8.7","event_points":17,"selected_by_percent":"23.1","now_cost":105,"minutes":569,"transfers_in":1466149,"goals_scored":5,"assists":3,"clean_sheets":1,"goals_conceded":12,"form":"8.2","value_season":"5.0","total_points":53,"minuteValue":0,"position":"Midfielder","value":5.0},{"second_name":"Werner","first_name":"Timo","team":"Chelsea","element_type":4,"ep_next":"8.5","ep_this":"8.5","event_points":7,"selected_by_percent":"24.0","now_cost":94,"minutes":695,"transfers_in":1018268,"goals_scored":4,"assists":2,"clean_sheets":3,"goals_conceded":9,"form":"8.0","value_season":"4.6","total_points":43,"minuteValue":0,"position":"Forward","value":4.6},{"second_name":"Kane","first_name":"Harry","team":"Spurs","element_type":4,"ep_next":"8.5","ep_this":"10.0","event_points":9,"selected_by_percent":"45.4","now_cost":110,"minutes":713,"transfers_in":2616320,"goals_scored":7,"assists":8,"clean_sheets":2,"goals_conceded":8,"form":"9.0","value_season":"7.3","total_points":80,"minuteValue":0,"position":"Forward","value":7.3},{"second_name":"Adams","first_name":"Che","team":"Southampton","element_type":4,"ep_next":"7.8","ep_this":"7.8","event_points":7,"selected_by_percent":"4.3","now_cost":59,"minutes":675,"transfers_in":295567,"goals_scored":3,"assists":3,"clean_sheets":4,"goals_conceded":11,"form":"7.8","value_season":"6.9","total_points":41,"minuteValue":0,"position":"Forward","value":6.9},{"second_name":"Zaha","first_name":"Wilfried","team":"Crystal Palace","element_type":3,"ep_next":"7.5","ep_this":"7.0","event_points":5,"selected_by_percent":"29.2","now_cost":74,"minutes":720,"transfers_in":2311449,"goals_scored":5,"assists":2,"clean_sheets":1,"goals_conceded":12,"form":"7.0","value_season":"7.3","total_points":54,"minuteValue":0,"position":"Midfielder","value":7.3}]'

In [90]:
fpl_html = df_slim_elements.head(10).to_html(index=False)

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>second_name</th>
      <th>first_name</th>
      <th>team</th>
      <th>element_type</th>
      <th>ep_next</th>
      <th>ep_this</th>
      <th>event_points</th>
      <th>selected_by_percent</th>
      <th>now_cost</th>
      <th>minutes</th>
      <th>transfers_in</th>
      <th>goals_scored</th>
      <th>assists</th>
      <th>clean_sheets</th>
      <th>goals_conceded</th>
      <th>form</th>
      <th>value_season</th>
      <th>total_points</th>
      <th>minuteValue</th>
      <th>position</th>
      <th>value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Ã–zil</td>
      <td>Mesut</td>
      <td>Arsenal</td>
      <td>3</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0</td>
      <td>0.6</td>
      <td>68</td>
      <td>0</td>
      <td>3310</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0</td>
      <td>0</td>
      <td>Midfielder</td>
      <td>0.0</td>
    </tr>
    <tr>
      <td>Papastathopoulos</td>
      <td>Sokratis</td>
      <td>Arsenal</td>
      <td>2</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0</td>
      <td>0.1</td>
      <td>49</td>
      <td>0</td>
      <td>10209</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0</td>
      <td>0</td>
      <td>Defender</td>
      <td>0.0</td>
    </tr>
    <tr>
      <td>Luiz Moreira Marinho</td>
      <td>David</td>
      <td>Arsenal</td>
      <td>2</td>
      <td>1.3</td>
      <td>1.3</td>
      <td>0</td>
      <td>0.9</td>
      <td>55</td>
      <td>319</td>
      <td>32892</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>5</td>
      <td>0.8</td>
      <td>1.3</td>
      <td>7</td>
      <td>0</td>
      <td>Defender</td>
      <td>1.3</td>
    </tr>
    <tr>
      <td>Aubameyang</td>
      <td>Pierre-Emerick</td>
      <td>Arsenal</td>
      <td>3</td>
      <td>4.0</td>
      <td>4.0</td>
      <td>2</td>
      <td>13.1</td>
      <td>117</td>
      <td>716</td>
      <td>412266</td>
      <td>2</td>
      <td>1</td>
      <td>2</td>
      <td>10</td>
      <td>3.5</td>
      <td>2.6</td>
      <td>30</td>
      <td>0</td>
      <td>Midfielder</td>
      <td>2.6</td>
    </tr>
    <tr>
      <td>Soares</td>
      <td>CÃ©dric</td>
      <td>Arsenal</td>
      <td>2</td>
      <td>0.5</td>
      <td>0.5</td>
      <td>0</td>
      <td>0.2</td>
      <td>47</td>
      <td>0</td>
      <td>2896</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0</td>
      <td>0</td>
      <td>Defender</td>
      <td>0.0</td>
    </tr>
    <tr>
      <td>Lacazette</td>
      <td>Alexandre</td>
      <td>Arsenal</td>
      <td>4</td>
      <td>2.0</td>
      <td>2.0</td>
      <td>2</td>
      <td>3.3</td>
      <td>84</td>
      <td>485</td>
      <td>262933</td>
      <td>3</td>
      <td>0</td>
      <td>2</td>
      <td>5</td>
      <td>1.5</td>
      <td>3.2</td>
      <td>27</td>
      <td>0</td>
      <td>Forward</td>
      <td>3.2</td>
    </tr>
    <tr>
      <td>Mustafi</td>
      <td>Shkodran</td>
      <td>Arsenal</td>
      <td>2</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>0</td>
      <td>0.0</td>
      <td>50</td>
      <td>44</td>
      <td>10725</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0.5</td>
      <td>0.4</td>
      <td>2</td>
      <td>0</td>
      <td>Defender</td>
      <td>0.4</td>
    </tr>
    <tr>
      <td>Leno</td>
      <td>Bernd</td>
      <td>Arsenal</td>
      <td>1</td>
      <td>4.0</td>
      <td>4.0</td>
      <td>2</td>
      <td>9.2</td>
      <td>50</td>
      <td>720</td>
      <td>373250</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
      <td>10</td>
      <td>3.5</td>
      <td>5.6</td>
      <td>28</td>
      <td>0</td>
      <td>Goalkeeper</td>
      <td>5.6</td>
    </tr>
    <tr>
      <td>Xhaka</td>
      <td>Granit</td>
      <td>Arsenal</td>
      <td>3</td>
      <td>1.3</td>
      <td>1.3</td>
      <td>0</td>
      <td>0.5</td>
      <td>53</td>
      <td>407</td>
      <td>21281</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>6</td>
      <td>0.8</td>
      <td>1.9</td>
      <td>10</td>
      <td>0</td>
      <td>Midfielder</td>
      <td>1.9</td>
    </tr>
    <tr>
      <td>MarÃ­</td>
      <td>Pablo</td>
      <td>Arsenal</td>
      <td>2</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0</td>
      <td>0.0</td>
      <td>44</td>
      <td>0</td>
      <td>286</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0</td>
      <td>0</td>
      <td>Defender</td>
      <td>0.0</td>
    </tr>
  </tbody>
</table>

In [ ]:
df_slim_elements = elements_df[['second_name','first_name','team','element_type', 'ep_next',
       'ep_this','event_points','selected_by_percent','now_cost','minutes','transfers_in','goals_scored',
       'assists','clean_sheets','goals_conceded','form','value_season','total_points','minuteValue']]